# Site
repository: djquazzi/djquazzi.github.io
favicon: images/favicon.ico

darkmode: true

# Personal info
name: Daniel Novello
title: Senior IT Specialist & Apple System Engineer
email: djquazzi@gmail.com
website: http://daniel.novello.co.za

# Social links
twitter_username: dasnizzel
github_username:  https://github.com/djquazzi/
linkedin_username: daniel-novello-70719917brant

# About Section
about_title: Professional Profile
about_profile_image: images/myAvatar.png
about_content: |
  A resourceful senior Apple Mac engineer and multi-skilled professional with over a decade and a half of focused information technology industry experience. 
  Used to working at all levels, from single user support through to organisational IT integration and management, working with a vast range of macOS, iOS and some open source devices. 
  Works well with professionals and clients across an organisation, striving to create safe and strong IT environments, regularly creating and communicating changes, and guiding junior staff towards ongoing success. 
  Utilises a large technical skillset alongside expert client liaison capabilities to maintain and continuously improve IT processes, troubleshoot and diagnose issues and tackle problems head-on. 
  Able to coordinate infrastructure strategy, develop comprehensive plans and handle all aspects of installation, testing and support for hardware, software and networks. 
  A self-starter who enjoys driving change and working on own initiative, with a pervasive desire to learn new things, adopting and integrate new technologies, processes and competencies swiftly and seamlessly.

# Projects Section
projects_title: Competencies

# Experience Section
experience_title: Career Summary

# Education Section
educaton_title: Education & Development

# More Section
more_title: References
more_content: 
  Available on request

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  style: compressed

plugins:
 - jekyll-seo-tag
